### PR TITLE
Add support for YouTube shorts in the YouTube regexp

### PR DESCRIPTION
**Pull request by Zingzy**
This PR addresses issue #206 

### Overview

-  Update the regex to add support for YouTube shorts

### Testing

Screenshot 2024-09-29 023356

### CODE REVIEW

**Review by Snailedlt — COMMENTED** [review]
Thanks for the PR!

Could you please also add some new URLs to the test file? 😊

**Comment by Zingzy** [comment]
> Thanks for the PR!
> 
> Could you please also add some new URLs to the test file? 😊

Sure, just needed a confirmation I need to add the URLs in [this file](https://github.com/Snailedlt/Markdown-Videos/blob/main/apps/api/tests/data_for_testing.py) right?

**Comment by Zingzy** [comment]
@Snailedlt I added the new URLs in the test file, please check

**Comment by Snailedlt** [comment]
@Zingzy doesn't work in the preview environment for some reason

**Comment by Zingzy** [comment]
> @Zingzy doesn't work in the preview environment for some reason 

@Snailedlt I was testing this branch locally and it was working fine, there must be some problem in the vercel deployment.. I even tested the updated regex with all of the YouTube shorts URLs.. I also visited the `markdown-videos-web` preview in the vercel test deployment and the API was able to detect YouTube shorts as expected

Screenshot_4-10-2024_173710_markdown-videos-api-git-fork-zingzy-f1895b-snailedlts-projects vercel app

**Comment by Snailedlt** [comment]
Hmm, I'll see if I can take a look this weekend. Might just need to redeploy the web app

**Comment by Snailedlt** [comment]
Ahh I see what the problem is. The environment variables go towards the prod API, so the changes don't affect the website 😅

**Comment by Zingzy** [comment]
> Ahh I see what the problem is. The environment variables go towards the prod API, so the changes don't affect the website 😅

No worries! Just glad to contribute to this amazing repo 😄

**Comment by Snailedlt** [comment]
@Zingzy I'm glad you enjoy it!
Thank you for the contribution, always enjoyable to review when everything is this tidy! 😊

Feel free to make issues or PRs if you find anything more that can be improved or fixed :)

**Comment by Zingzy** [comment]
> @Zingzy I'm glad you enjoy it! Thank you for the contribution, always enjoyable to review when everything is this tidy! 😊
> 
> Feel free to make issues or PRs if you find anything more that can be improved or fixed :)

Thank you, I would also love to contribute to issue #11 😊

**Comment by Snailedlt** [comment]
@Zingzy awesome!
Feel free to work with any issue you'd like 😊
I assigned #11 to you

**Pull request merged**
